import type { ContentCalendarItem } from '../types/contentCalendar';

export const MOCK_CONTENT_CALENDAR_ITEMS: ContentCalendarItem[] = [
  // 1. Apex Transfers
  {
    id: 'mock-01',
    serial: 'APX-101',
    client_name: 'Apex Transfers',
    campaign_type: 'Airport Transfer Promo',
    creative_type: 'Reel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Promotional',
    content_concept: 'Never Miss a Flight: Luxury Airport Fleet',
    offer: '15% Off First Booking',
    cta: 'Book Now in Bio',
    approval_status: 'Approved for Campaign',
    setup_status: 'Ready',
    stage: 'Ready to Post',
    publish_date: '2026-10-08',
    channels: ['Instagram', 'TikTok'],
    assignee_id: 'usr-01',
    assignee_name: 'Sarah Jenkins',
    design_owner: 'Hamza Tariq',
    design_due: '2026-10-07',
    created_at: '2026-10-01T09:00:00Z',
    updated_at: '2026-10-05T14:30:00Z',
  },
  {
    id: 'mock-02',
    serial: 'APX-102',
    client_name: 'Apex Transfers',
    campaign_type: 'Customer Testimonial',
    creative_type: 'Carousel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Social Proof',
    content_concept: 'VIP Chauffeur Experience: Client Review',
    offer: 'None',
    cta: 'Swipe to See Reviews',
    approval_status: 'Posted',
    setup_status: 'Completed',
    stage: 'Posted',
    publish_date: '2026-10-03',
    channels: ['Instagram', 'LinkedIn'],
    assignee_id: 'usr-02',
    assignee_name: 'Hamza Tariq',
    design_owner: 'Hamza Tariq',
    created_at: '2026-09-28T11:00:00Z',
    updated_at: '2026-10-03T16:00:00Z',
  },
  {
    id: 'mock-03',
    serial: 'APX-103',
    client_name: 'Apex Transfers',
    campaign_type: 'Corporate Travel Solutions',
    creative_type: 'Static Image',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'B2B Advantage',
    content_concept: 'Corporate Fleet Accounts for Executives',
    offer: 'Free Corporate Account Setup',
    cta: 'Contact Corporate Desk',
    approval_status: 'Changes Requested',
    setup_status: 'Draft',
    stage: 'Content Revision',
    publish_date: '2026-10-04', // Overdue!
    channels: ['LinkedIn'],
    assignee_id: 'usr-01',
    assignee_name: 'Sarah Jenkins',
    design_owner: 'Ayesha Khan',
    design_due: '2026-10-03',
    created_at: '2026-09-29T10:00:00Z',
    updated_at: '2026-10-05T09:15:00Z',
  },
  {
    id: 'mock-04',
    serial: 'APX-104',
    client_name: 'Apex Transfers',
    campaign_type: 'Fleet Showcase',
    creative_type: 'Video',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Brand Awareness',
    content_concept: 'Inside the 2026 Mercedes S-Class Interior',
    offer: 'None',
    cta: 'Watch Full Tour',
    approval_status: 'Creative Client Review',
    setup_status: 'In Review',
    stage: 'Creative Client Review',
    publish_date: '2026-10-12',
    channels: ['Instagram', 'YouTube'],
    assignee_id: 'usr-02',
    assignee_name: 'Hamza Tariq',
    design_owner: 'Hamza Tariq',
    created_at: '2026-10-02T13:00:00Z',
    updated_at: '2026-10-06T10:00:00Z',
  },

  // 2. Reamarc
  {
    id: 'mock-05',
    serial: 'RMC-201',
    client_name: 'Reamarc',
    campaign_type: 'Product Launch',
    creative_type: 'Motion Graphics',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Product Feature',
    content_concept: 'Next-Gen Attendance & Geofence Intelligence',
    offer: 'Free Enterprise Demo',
    cta: 'Schedule Demo',
    approval_status: 'Posted',
    setup_status: 'Completed',
    stage: 'Posted',
    publish_date: '2026-10-02',
    channels: ['LinkedIn', 'Twitter'],
    assignee_id: 'usr-03',
    assignee_name: 'Michael Vance',
    design_owner: 'Michael Vance',
    created_at: '2026-09-25T10:00:00Z',
    updated_at: '2026-10-02T18:00:00Z',
  },
  {
    id: 'mock-06',
    serial: 'RMC-202',
    client_name: 'Reamarc',
    campaign_type: 'Case Study',
    creative_type: 'Carousel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Case Study',
    content_concept: 'How Apex Reduced Payroll Processing by 40%',
    offer: 'Download PDF Report',
    cta: 'Read Case Study',
    approval_status: 'Approved for Campaign',
    setup_status: 'Ready',
    stage: 'Ready to Post',
    publish_date: '2026-10-09',
    channels: ['LinkedIn'],
    assignee_id: 'usr-04',
    assignee_name: 'Zain Ali',
    design_owner: 'Ayesha Khan',
    created_at: '2026-10-01T15:00:00Z',
    updated_at: '2026-10-06T11:00:00Z',
  },
  {
    id: 'mock-07',
    serial: 'RMC-203',
    client_name: 'Reamarc',
    campaign_type: 'Feature Spotlight',
    creative_type: 'Static Image',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Educational',
    content_concept: '3 Ways to Prevent Time Theft in 2026',
    offer: 'None',
    cta: 'Save This Post',
    approval_status: 'Content Client Review',
    setup_status: 'Draft',
    stage: 'Content Client Review',
    publish_date: '2026-10-14',
    channels: ['Instagram', 'LinkedIn'],
    assignee_id: 'usr-01',
    assignee_name: 'Sarah Jenkins',
    created_at: '2026-10-04T08:30:00Z',
    updated_at: '2026-10-05T12:00:00Z',
  },

  // 3. Lexus Tower
  {
    id: 'mock-08',
    serial: 'LXT-301',
    client_name: 'Lexus Tower',
    campaign_type: 'Real Estate Luxury Penthouse',
    creative_type: 'Reel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Property Showcase',
    content_concept: 'Skyline Penthouse Tour with Panoramic Views',
    offer: 'Private Viewing Available',
    cta: 'DM for Private Viewing',
    approval_status: 'Approved for Campaign',
    setup_status: 'Ready',
    stage: 'Ready to Post',
    publish_date: '2026-10-07',
    channels: ['Instagram', 'TikTok'],
    assignee_id: 'usr-02',
    assignee_name: 'Hamza Tariq',
    design_owner: 'Hamza Tariq',
    created_at: '2026-10-02T10:00:00Z',
    updated_at: '2026-10-06T09:00:00Z',
  },
  {
    id: 'mock-09',
    serial: 'LXT-302',
    client_name: 'Lexus Tower',
    campaign_type: 'Investment Opportunity',
    creative_type: 'Carousel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Financial ROI',
    content_concept: 'Guaranteed 8.5% Rental Yield in Downtown',
    offer: 'Flexible 4-Year Payment Plan',
    cta: 'Download Payment Schedule',
    approval_status: 'Creative Production',
    setup_status: 'In Production',
    stage: 'Creative Production',
    publish_date: '2026-10-15',
    channels: ['Instagram', 'Facebook'],
    assignee_id: 'usr-05',
    assignee_name: 'Ayesha Khan',
    design_owner: 'Ayesha Khan',
    created_at: '2026-10-03T11:00:00Z',
    updated_at: '2026-10-05T17:00:00Z',
  },
  {
    id: 'mock-10',
    serial: 'LXT-303',
    client_name: 'Lexus Tower',
    campaign_type: 'Architectural Design',
    creative_type: 'Static Image',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Luxury Lifestyle',
    content_concept: 'World-Class Amenities: Infinity Pool & Spa',
    offer: 'None',
    cta: 'Explore Living',
    approval_status: 'Review Content',
    setup_status: 'Draft',
    stage: 'Content Internal Review',
    publish_date: '2026-10-18',
    channels: ['Instagram'],
    assignee_id: 'usr-01',
    assignee_name: 'Sarah Jenkins',
    created_at: '2026-10-05T14:00:00Z',
    updated_at: '2026-10-06T08:00:00Z',
  },

  // 4. Elegant Design & Construction
  {
    id: 'mock-11',
    serial: 'EDC-401',
    client_name: 'Elegant Design & Construction',
    campaign_type: 'Modern Villa Reveal',
    creative_type: 'Video',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Portfolio Showcase',
    content_concept: 'Turnkey 10,000 sq ft Villa Walkthrough',
    offer: 'Free Architectural Consultation',
    cta: 'Book Design Session',
    approval_status: 'Posted',
    setup_status: 'Completed',
    stage: 'Posted',
    publish_date: '2026-10-01',
    channels: ['Instagram', 'YouTube'],
    assignee_id: 'usr-02',
    assignee_name: 'Hamza Tariq',
    design_owner: 'Hamza Tariq',
    created_at: '2026-09-24T10:00:00Z',
    updated_at: '2026-10-01T17:00:00Z',
  },
  {
    id: 'mock-12',
    serial: 'EDC-402',
    client_name: 'Elegant Design & Construction',
    campaign_type: 'Behind the Build',
    creative_type: 'Reel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Craftsmanship',
    content_concept: 'Italian Marble Installation Time-Lapse',
    offer: 'None',
    cta: 'Follow for Luxury Builds',
    approval_status: 'Creative Revision',
    setup_status: 'Changes Requested',
    stage: 'Creative Revision',
    publish_date: '2026-10-05', // Overdue!
    channels: ['Instagram', 'TikTok'],
    assignee_id: 'usr-02',
    assignee_name: 'Hamza Tariq',
    design_owner: 'Hamza Tariq',
    design_due: '2026-10-04',
    created_at: '2026-09-30T16:00:00Z',
    updated_at: '2026-10-06T12:00:00Z',
  },

  // 5. Seven Star Mall
  {
    id: 'mock-13',
    serial: 'SSM-501',
    client_name: 'Seven Star Mall',
    campaign_type: 'Grand Opening Announcement',
    creative_type: 'Carousel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Event & Retail',
    content_concept: 'Top 10 Global Brands Opening This Weekend',
    offer: 'Opening Weekend Discounts up to 50%',
    cta: 'Visit Us This Friday',
    approval_status: 'Approved for Campaign',
    setup_status: 'Ready',
    stage: 'Ready to Post',
    publish_date: '2026-10-09',
    channels: ['Facebook', 'Instagram'],
    assignee_id: 'usr-04',
    assignee_name: 'Zain Ali',
    design_owner: 'Ayesha Khan',
    created_at: '2026-10-02T10:00:00Z',
    updated_at: '2026-10-06T13:00:00Z',
  },
  {
    id: 'mock-14',
    serial: 'SSM-502',
    client_name: 'Seven Star Mall',
    campaign_type: 'Food Court Foodie Tour',
    creative_type: 'Reel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Lifestyle & Dining',
    content_concept: 'What \$20 Gets You at Seven Star Food Court',
    offer: 'None',
    cta: 'Tag Your Foodie Friend',
    approval_status: 'Creative Client Review',
    setup_status: 'In Review',
    stage: 'Creative Client Review',
    publish_date: '2026-10-11',
    channels: ['Instagram', 'TikTok'],
    assignee_id: 'usr-02',
    assignee_name: 'Hamza Tariq',
    design_owner: 'Hamza Tariq',
    created_at: '2026-10-03T14:00:00Z',
    updated_at: '2026-10-06T09:30:00Z',
  },

  // 6. Valencia Heights/Centrum Group – PlanetX
  {
    id: 'mock-15',
    serial: 'VHC-601',
    client_name: 'Valencia Heights/Centrum Group – PlanetX',
    campaign_type: 'Commercial Leasing',
    creative_type: 'Static Image',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Corporate Spaces',
    content_concept: 'Grade-A Office Floors Available for MNCs',
    offer: 'Custom Fit-Out Subsidies',
    cta: 'Inquire Today',
    approval_status: 'Content Client Review',
    setup_status: 'Draft',
    stage: 'Content Client Review',
    publish_date: '2026-10-13',
    channels: ['LinkedIn'],
    assignee_id: 'usr-01',
    assignee_name: 'Sarah Jenkins',
    created_at: '2026-10-04T11:00:00Z',
    updated_at: '2026-10-05T15:00:00Z',
  },
  {
    id: 'mock-16',
    serial: 'VHC-602',
    client_name: 'Valencia Heights/Centrum Group – PlanetX',
    campaign_type: 'Residential Launch',
    creative_type: 'Video',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Community Living',
    content_concept: 'Experience Green Living at Valencia Heights',
    offer: 'Zero Down Payment Special',
    cta: 'Register Interest',
    approval_status: 'Posted',
    setup_status: 'Completed',
    stage: 'Posted',
    publish_date: '2026-09-30',
    channels: ['Instagram', 'Facebook'],
    assignee_id: 'usr-03',
    assignee_name: 'Michael Vance',
    design_owner: 'Michael Vance',
    created_at: '2026-09-20T10:00:00Z',
    updated_at: '2026-09-30T19:00:00Z',
  },

  // 7. AK Group/ Park Oaks
  {
    id: 'mock-17',
    serial: 'AKG-701',
    client_name: 'AK Group/ Park Oaks',
    campaign_type: 'Golf Course Residences',
    creative_type: 'Carousel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Luxury Real Estate',
    content_concept: 'Wake Up to 18-Hole Championship Views',
    offer: 'Early Bird Pricing',
    cta: 'Download Brochure',
    approval_status: 'Creative Production',
    setup_status: 'In Production',
    stage: 'Creative Production',
    publish_date: '2026-10-16',
    channels: ['Instagram', 'LinkedIn'],
    assignee_id: 'usr-05',
    assignee_name: 'Ayesha Khan',
    design_owner: 'Ayesha Khan',
    created_at: '2026-10-04T12:00:00Z',
    updated_at: '2026-10-06T10:00:00Z',
  },
  {
    id: 'mock-18',
    serial: 'AKG-702',
    client_name: 'AK Group/ Park Oaks',
    campaign_type: 'Construction Update',
    creative_type: 'Static Image',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Milestone Update',
    content_concept: 'Tower B Structure 100% Completed on Schedule',
    offer: 'None',
    cta: 'View Progress Photos',
    approval_status: 'Approved for Campaign',
    setup_status: 'Ready',
    stage: 'Ready to Post',
    publish_date: '2026-10-10',
    channels: ['Facebook', 'LinkedIn'],
    assignee_id: 'usr-04',
    assignee_name: 'Zain Ali',
    design_owner: 'Ayesha Khan',
    created_at: '2026-10-03T15:00:00Z',
    updated_at: '2026-10-06T11:30:00Z',
  },

  // 8. Gemcon Engineering
  {
    id: 'mock-19',
    serial: 'GCE-801',
    client_name: 'Gemcon Engineering',
    campaign_type: 'Infrastructure Mega Projects',
    creative_type: 'Video',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Industrial Authority',
    content_concept: 'Engineering the Metropolis: Coastal Bridge Project',
    offer: 'None',
    cta: 'Read Engineering Whitepaper',
    approval_status: 'Posted',
    setup_status: 'Completed',
    stage: 'Posted',
    publish_date: '2026-10-01',
    channels: ['LinkedIn', 'YouTube'],
    assignee_id: 'usr-03',
    assignee_name: 'Michael Vance',
    design_owner: 'Michael Vance',
    created_at: '2026-09-22T09:00:00Z',
    updated_at: '2026-10-01T15:00:00Z',
  },
  {
    id: 'mock-20',
    serial: 'GCE-802',
    client_name: 'Gemcon Engineering',
    campaign_type: 'Safety First Culture',
    creative_type: 'Static Image',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Culture & Standards',
    content_concept: '5 Million Safe Working Hours Milestone',
    offer: 'None',
    cta: 'Celebrate With Us',
    approval_status: 'Content Internal Review',
    setup_status: 'Draft',
    stage: 'Content Internal Review',
    publish_date: '2026-10-17',
    channels: ['LinkedIn'],
    assignee_id: 'usr-01',
    assignee_name: 'Sarah Jenkins',
    created_at: '2026-10-05T16:00:00Z',
    updated_at: '2026-10-06T09:00:00Z',
  },

  // 9. Unassigned / Urgent Edge Case Items
  {
    id: 'mock-21',
    serial: 'MM-901',
    client_name: 'MM Solutions',
    campaign_type: 'Cybersecurity Month',
    creative_type: 'Carousel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Security Advice',
    content_concept: '5 Critical Zero-Day Vulnerabilities to Patch Now',
    offer: 'Free Threat Assessment',
    cta: 'Scan Your Network',
    approval_status: 'Changes Requested',
    setup_status: 'Draft',
    stage: 'Content Revision',
    publish_date: '2026-10-03', // Overdue!
    channels: ['LinkedIn'],
    assignee_id: null,
    assignee_name: null,
    created_at: '2026-09-27T10:00:00Z',
    updated_at: '2026-10-05T16:00:00Z',
  },
  {
    id: 'mock-22',
    serial: 'DBL-902',
    client_name: 'DBL',
    campaign_type: 'Logistics Fleet Tracking',
    creative_type: 'Reel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Supply Chain Efficiency',
    content_concept: 'Real-Time Temperature Monitoring for Cold Chain',
    offer: 'Book Fleet Pilot',
    cta: 'Learn More',
    approval_status: 'Creative Client Review',
    setup_status: 'In Review',
    stage: 'Creative Client Review',
    publish_date: '2026-10-12',
    channels: ['Instagram', 'LinkedIn'],
    assignee_id: 'usr-02',
    assignee_name: 'Hamza Tariq',
    design_owner: 'Hamza Tariq',
    created_at: '2026-10-03T10:00:00Z',
    updated_at: '2026-10-06T10:00:00Z',
  },
  {
    id: 'mock-23',
    serial: 'PGI-903',
    client_name: 'Pakistan Global Institute(PGI)',
    campaign_type: 'Fall Admissions 2026',
    creative_type: 'Carousel',
    content_type: 'Scheduled',
    creative_category: 'Organic Creative',
    content_pillar: 'Academics & Careers',
    content_concept: 'BS Artificial Intelligence & Data Science Applications Open',
    offer: 'Merit Scholarships up to 75%',
    cta: 'Apply Online',
    approval_status: 'Approved for Campaign',
    setup_status: 'Ready',
    stage: 'Ready to Post',
    publish_date: '2026-10-08',
    channels: ['Instagram', 'Facebook', 'LinkedIn'],
    assignee_id: 'usr-04',
    assignee_name: 'Zain Ali',
    design_owner: 'Ayesha Khan',
    created_at: '2026-10-01T10:00:00Z',
    updated_at: '2026-10-06T09:00:00Z',
  },
];
